const SOCKET_EVENTS = {
  CONNECTION: "connection",
  DISCONNECT: "disconnect",

  QUEUE_UPDATED: "QUEUE_UPDATED",
  BARBER_STATUS_CHANGED: "BARBER_STATUS_CHANGED",

  CUSTOMER_JOINED: "CUSTOMER_JOINED",
  CUSTOMER_CALLED: "CUSTOMER_CALLED",
  CUSTOMER_COMPLETED: "CUSTOMER_COMPLETED",
  CUSTOMER_SKIPPED: "CUSTOMER_SKIPPED",
  CUSTOMER_CANCELLED: "CUSTOMER_CANCELLED",

  DASHBOARD_UPDATED: "DASHBOARD_UPDATED",

  JOIN_BARBER_ROOM: "JOIN_BARBER_ROOM",
  JOIN_ADMIN_ROOM: "JOIN_ADMIN_ROOM",
};

module.exports = SOCKET_EVENTS;