const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const http = require('node:http');
const mongoose = require('mongoose');
const { MongoMemoryReplSet } = require('mongodb-memory-server');
process.env.JWT_SECRET = crypto.randomBytes(48).toString('hex');
process.env.NODE_ENV = 'production';
process.env.CLIENT_URL = 'http://localhost:5173';
process.env.MONGOMS_DOWNLOAD_DIR ||= require('node:path').resolve(__dirname, '../.cache/mongodb');
let repl, server, io;
let count = 0;
const sockets = [];
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
async function main() {
 if (process.env.TEST_MONGO_URI) {
   const dbName = new URL(process.env.TEST_MONGO_URI).pathname.slice(1);
   if (!dbName.startsWith('barberqueue_test_')) throw new Error('TEST_MONGO_URI must name a disposable barberqueue_test_* database.');
   process.env.MONGO_URI = process.env.TEST_MONGO_URI;
 }
 else { repl = await MongoMemoryReplSet.create({ replSet: { count: 1 }, binary: { version: '8.2.0' } }); process.env.MONGO_URI = repl.getUri(); }
 await require('../config/db')();
 const User = require('../models/User'), Barber = require('../models/Barber'), Queue = require('../models/Queue');
 await Promise.all([User.init(), Barber.init(), Queue.init()]);
 const password = crypto.randomBytes(16).toString('hex');
 const admin = await User.create({ name: 'Test Admin', email: 'admin@example.test', password: await require('bcrypt').hash(password, 10), role: 'ADMIN' });
 server = http.createServer(require('../app')); io = require('../services/socketService').initializeSocket(server);
 await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
 const base = 'http://127.0.0.1:' + server.address().port;
 async function call(method, path, body, token, expected = 200) {
   const response = await fetch(base + '/api' + path, { method, headers: { 'Content-Type':'application/json', ...(token ? { Authorization: 'Bearer '+token } : {}) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
   const data = await response.json(); assert.equal(response.status, expected, method+' '+path+' '+JSON.stringify(data)); count++; return data;
 }
 await call('POST','/auth/register-admin',{},null,401);
 await call('POST','/auth/login',{ email: { $ne: null }, password },null,400);
 const a = await call('POST','/auth/login',{ email: 'ADMIN@example.test', password });
 assert(!JSON.stringify(a).includes(password));
 await call('GET','/admin/dashboard',undefined,null,401);
 const make = async (n) => (await call('POST','/barbers',{ name: 'Barber '+n,email: 'barber'+n+'@example.test',password,displayName:'Barber '+n,chairNumber:n, phone:'900000000'+n, experience:2 },a.token,201)).barber;
 const b1 = await make(1), b2 = await make(2);
 const b = await call('POST','/auth/login',{ email:'barber1@example.test',password });
 const bOther = await call('POST','/auth/login',{email:'barber2@example.test',password});
 const connect = async token => {
   const socket = require('socket.io-client').io(base, { auth: { token }, reconnection:false }); sockets.push(socket);
   await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);}); return socket;
 };
 const adminSocket = await connect(a.token), ownSocket = await connect(b.token), otherSocket = await connect(bOther.token);
 await assert.rejects(connect('bad-token')); count++;
 otherSocket.emit('JOIN_BARBER_ROOM', b1._id); otherSocket.emit('JOIN_ADMIN_ROOM');
 await delay(100);
 const events = [[],[],[]]; [adminSocket,ownSocket,otherSocket].forEach((socket,index)=>socket.on('QUEUE_UPDATED',payload=>events[index].push(payload)));
 require('../services/socketService').emitQueueUpdate(b1._id,{event:'CUSTOMER_JOINED',customer:{phone:'DO-NOT-BROADCAST',accessToken:'DO-NOT-BROADCAST'}});
 await delay(100);
 assert.equal(events[0].length,1);assert.equal(events[1].length,1);assert.equal(events[2].length,0);
 assert(!JSON.stringify(events).includes('DO-NOT-BROADCAST'));count+=4;

 await call('GET','/auth/me',undefined,b.token);
 await call('GET','/admin/dashboard',undefined,b.token,403);
 await call('POST','/auth/register-admin',{name:'Other',email:'other@example.test',password},b.token,403);
 await call('GET','/queue/'+b2._id,undefined,b.token,403);
 await call('PATCH','/barbers/'+b2._id+'/status',{status:'BREAK'},b.token,403);
 await call('PATCH','/barbers/'+b1._id+'/status',{status:'INVALID'},b.token,400);
 await call('GET','/queue/not-an-id',undefined,b.token,400);
 await call('GET','/auth/me',undefined,'bad-token',401);
 const expired = require('jsonwebtoken').sign({id:admin._id},process.env.JWT_SECRET,{expiresIn:-1});
 await call('GET','/auth/me',undefined,expired,401);
 const q1 = (await call('POST','/queue/join',{ barberId:b1._id,customerName:'First Customer',phone:'9111111111'},null,201)).data.queue;
 assert.match(q1.accessToken,/^[a-f0-9]{64}$/);
 await call('POST','/queue/join',{barberId:b2._id,customerName:'Duplicate',phone:'9111111111'},null,409);
 const q2 = (await call('POST','/queue/join',{ barberId:b2._id,customerName:'Other Customer',phone:'9222222222'},null,201)).data.queue;
 assert.equal(q1.tokenNumber,q2.tokenNumber); assert.notEqual(q1.accessToken,q2.accessToken);
 await call('GET','/queue/status/1',undefined,null,400);
 const status = await call('GET','/queue/status/'+q1.accessToken);
 assert.equal(status.data.barber._id,b1._id); assert.equal(status.data.estimatedWait,0);
 assert(!JSON.stringify(status).includes('phone'));
 await call('PATCH','/queue/cancel/'+q2._id,{},b.token,403);
 await call('PATCH','/queue/public/cancel',{accessToken:'0'.repeat(64)},null,404);
 await call('DELETE','/barbers/'+b1._id,undefined,a.token,409);
 await call('PATCH','/queue/'+b1._id+'/next',{},b.token);
 await call('PATCH','/queue/'+b1._id+'/next',{},b.token,409);
 await call('PATCH','/queue/public/cancel',{accessToken:q1.accessToken},null,409);
 await call('PATCH','/barbers/'+b1._id+'/status',{status:'AVAILABLE'},b.token,409);
 await call('PATCH','/queue/'+b1._id+'/finish',{queueId:q1._id},b.token);
 await call('PATCH','/queue/skip/'+q1._id,{},b.token,409);
 assert.equal((await call('GET','/queue/status/'+q1.accessToken)).data.status,'COMPLETED');
 await call('PATCH','/queue/public/cancel',{accessToken:q2.accessToken});
 assert.equal((await call('GET','/queue/status/'+q2.accessToken)).data.status,'CANCELLED');
 const service = require('../services/queueService');
 const joined = await Promise.all(Array.from({length:6},(_,n)=>service.joinQueue({barberId:b1._id,customerName:'Concurrent '+n,phone:'933333333'+n})));
 assert.equal(new Set(joined.map(q=>q.queue.tokenNumber)).size,6); count++;
 const duplicate = await Promise.allSettled([b1,b2].map(barber=>service.joinQueue({barberId:barber._id,customerName:'Same phone',phone:'9444444444'})));
 assert.equal(duplicate.filter(r=>r.status==='fulfilled').length,1); count++;
 const operations = await Promise.allSettled([service.callNextCustomer(b1._id),service.callNextCustomer(b1._id)]);
 assert.equal(operations.filter(r=>r.status==='fulfilled').length,1); count++;
 assert.equal(await Queue.countDocuments({barber:b1._id,status:'SERVING'}),1);
 const serving = await Queue.findOne({barber:b1._id,status:'SERVING'});
 await call('PATCH','/queue/'+b1._id+'/finish',{queueId:q1._id},b.token,409);
 assert.equal(await Queue.countDocuments({barber:b1._id,status:'SERVING'}),1);count++;
 await call('PATCH','/queue/'+b1._id+'/finish',{},b.token,400);
 await call('PATCH','/queue/skip/'+serving._id,{},b.token);
 for (const entry of await Queue.find({ status: { $in:['WAITING','SERVING'] } })) await service.cancelQueue(entry._id,admin);
 await call('PATCH','/barbers/'+b1._id+'/status',{status:'BREAK'},b.token);
 await call('POST','/queue/join',{barberId:b1._id,customerName:'Break Customer',phone:'9555555555'},null,409);
 await call('PUT','/barbers/'+b1._id,{displayName:'Updated Barber',phone:'',specialization:'Cuts'},a.token);
 await call('GET','/barbers/'+b1._id,undefined,a.token);
 await call('GET','/barbers/dashboard',undefined,b.token);
 await call('GET','/queue/'+b1._id+'/analytics',undefined,a.token);
 await call('GET','/queue/'+b1._id+'/summary',undefined,b.token);
 await call('GET','/admin/statistics',undefined,a.token);
 await call('GET','/customer/home');
 await call('DELETE','/barbers/'+b1._id,undefined,a.token);
 await delay(100); assert.equal(ownSocket.connected,false); count++;
 await call('GET','/barbers/dashboard',undefined,b.token,401);
 assert(await User.exists({_id:b1.user})); assert(await Queue.exists({barber:b1._id}));
 await call('PUT','/barbers/'+b1._id,{isActive:true},a.token);
 await call('GET','/barbers/dashboard',undefined,b.token);
 await call('GET','/docs',undefined,null,404);
 await call('GET','/unknown',undefined,null,404);
 const cors = await fetch(base+'/api/customer/home',{headers:{Origin:'https://untrusted.example'}});
 assert.equal(cors.headers.get('access-control-allow-origin'),null); count++;
 assert((await Queue.find()).every(q=>q.accessTokenHash === undefined && q.activePhone === undefined));
 assert((await User.find()).every(u=>u.password === undefined));
 console.info('PASS: '+count+' API/security/concurrency checks.');
}
main().catch(error => { console.error(error); process.exitCode=1; }).finally(async () => {
 for(const socket of sockets) socket.disconnect();
 if(io) await new Promise(resolve=>io.close(resolve));
 if(server?.listening) await new Promise(resolve=>server.close(resolve));
 await mongoose.disconnect(); if(repl) await repl.stop();
});
